version: "3"

tasks:
  install:
    cmd: go mod tidy
  fmt:
    cmds:
      - go fmt ./...
      - task: lint
  test:
    env:
      SIMULATON_TEST: true
    cmds:
      - docker pull mysql:latest
      - go test -cover -json -failfast ./... | tparse -all -progress  -smallscreen

  build:
    cmds:
      - go build -o unkey ./main.go

  generate:
    cmds:
      - go generate ./...
      - buf generate

  lint:
    cmds:
      - golangci-lint run
